apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mywiki.fullname" . }}
  labels:
    {{- include "mywiki.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mywiki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mywiki.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mywiki.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if eq .Values.upgrade "Yes"}}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
            - key: LocalSettings.php
              path: LocalSettings.php
      {{ end }}  
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{ if eq .Values.upgrade "Yes"}}    
          volumeMounts:
            - name: config
              mountPath: /var/www/html/LocalSettings.php
              subPath: LocalSettings.php
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
